"""Emit every number the paper reports, as LaTeX table bodies and a summary.

Writes REVISION_RESULTS.md at the repository root. Reads only the generated
results files, so the report cannot drift from the run that produced it: if a
number appears in the paper and not here, it has no source.

Makes no API calls.
"""

import json
import os
from datetime import date

import config
from metrics import is_generator_refusal

CATEGORY_LABELS = {
    "factual": "Factual",
    "reasoning": "Reasoning",
    "comparative": "Comparative",
    "numeric": "Numeric",
    "in_domain_hard": "In-domain hard",
    "near_miss": "Near-miss unanswerable",
    "out_of_domain": "Out-of-domain",
}

ANSWERABLE_LABELS = {
    "True": "true",
    "False": "false",
    "uncertain": "uncertain",
}


def read(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def fmt(value, places=2):
    return "--" if value is None else "{:.{p}f}".format(value, p=places)


def main():
    numbers = read(config.PAPER_NUMBERS_FILE)
    sweep = read(config.THRESHOLD_EXPERIMENT_FILE)
    selected = read(config.SELECTED_THRESHOLD_FILE)
    records = read(config.PER_QUERY_FILE)
    queries = read(config.QUERIES_FILE)
    chunks = read(config.CHUNKS_FILE)
    raw = read(config.RAW_DATASET_FILE)

    variants_path = os.path.join(config.RESULTS_DIR, "variants.json")
    variants = read(variants_path) if os.path.exists(variants_path) else None

    tau = numbers["selected_threshold"]
    c = numbers["baseline_comparison"]
    r = numbers["retrieval"]
    a = numbers["abstention_at_selected"]

    pages = sorted({s["page"] for s in raw})
    L = []
    w = L.append

    w("# Revision results")
    w("")
    w("Generated by `src/paper_tables.py` on {} from the files in `results/`. "
      "Every number below has a source in that directory; nothing here is "
      "hand-entered.".format(date.today().isoformat()))
    w("")
    w("| Setting | Value |")
    w("|---|---|")
    w("| Wikipedia pages | {} |".format(len(pages)))
    w("| Sections | {} |".format(len(raw)))
    w("| Passages (chunks) | {} |".format(len(chunks)))
    w("| Chunk size / overlap | {} / {} characters |".format(
        config.CHUNK_SIZE, config.CHUNK_OVERLAP))
    w("| Embedding model | `{}` |".format(config.EMBED_MODEL))
    w("| Retrieved passages *k* | {} |".format(config.TOP_K))
    w("| Generator | `{}` |".format(config.GENERATOR_MODEL))
    w("| Judge | `{}` (all experiments) |".format(config.JUDGE_MODEL))
    w("| Queries | {} |".format(len(queries)))
    w("| Selected threshold tau* | **{}** |".format(tau))
    w("")

    # ---------------------------------------------------------- Table I
    w("## Table I -- Query set composition (N = {})".format(len(queries)))
    w("")
    counts = {}
    for q in queries:
        key = (q["category"], str(q["answerable"]))
        counts[key] = counts.get(key, 0) + 1
    w("```latex")
    w("Category & $n$ & Answerable & Purpose \\\\")
    w("\\midrule")
    purpose = {
        "factual": "retrieval/generation",
        "reasoning": "retrieval/generation",
        "comparative": "retrieval/generation",
        "numeric": "retrieval/generation",
        "in_domain_hard": "stress test",
        "near_miss": "abstention test (hard)",
        "out_of_domain": "abstention test (easy)",
    }
    for cat in ["factual", "reasoning", "comparative", "numeric",
                "in_domain_hard", "near_miss", "out_of_domain"]:
        for (c_, ans), n in sorted(counts.items()):
            if c_ == cat:
                w("{} & {} & {} & {} \\\\".format(
                    CATEGORY_LABELS[cat], n, ANSWERABLE_LABELS[ans], purpose[cat]))
    w("```")
    w("")

    # --------------------------------------------------------- Table II
    w("## Table II -- RAG vs. baseline (N = {}, tau = {})".format(c["n"], tau))
    w("")
    w("| Metric | RAG | Baseline |")
    w("|---|---:|---:|")
    w("| Relevance (overall) | {} | {} |".format(
        fmt(c["rag_relevance_overall"]), fmt(c["baseline_relevance"])))
    w("| Relevance (answered only, n={}) | {} | -- |".format(
        c["rag_n_answered"], fmt(c["rag_relevance_answered"])))
    w("| Faithfulness (overall) | **{}** | **{}** |".format(
        fmt(c["rag_faithfulness"]), fmt(c["baseline_faithfulness"])))
    w("| Faithfulness (answered only) | {} | -- |".format(
        fmt(c["rag_faithfulness_answered"])))
    w("| Hallucination rate (faithfulness < {:.0f}) | {}/{} = {} | {}/{} = {} |".format(
        config.HALLUCINATION_FAITHFULNESS_CUTOFF,
        c["rag_hallucinations"], c["rag_n_substantive"],
        fmt(c["rag_hallucination_rate"]),
        c["baseline_hallucinations"], c["baseline_n_substantive"],
        fmt(c["baseline_hallucination_rate"])))
    w("| Abstain rate | {:.2%} | -- |".format(c["abstain_rate"]))
    w("| Generator-side refusals | {}/{} | -- |".format(
        c["rag_generator_refusals"], c["rag_n_answered"]))
    w("")
    w("Hallucination denominators exclude refusals on both sides: a refusal "
      "asserts nothing, and the judge is not self-consistent when scoring one.")
    w("")

    # -------------------------------------------------------- Table III
    w("## Table III -- Retrieval quality")
    w("")
    w("| Metric | Value |")
    w("|---|---:|")
    w("| n (queries carrying ground-truth keywords) | {} |".format(r["n_queries"]))
    w("| Hit@{} | {} |".format(r["k"], fmt(r["hit@k"])))
    w("| Precision@{} | {} |".format(r["k"], fmt(r["precision@k"])))
    w("| MRR@{} | {} |".format(r["k"], fmt(r["mrr@k"])))
    w("")
    w("None of these vary with tau: the gate decides whether retrieved context "
      "is used, not what is retrieved.")
    w("")

    # --------------------------------------------------------- Table IV
    w("## Table IV -- Threshold sweep")
    w("")
    w("Selection rule: {}.".format(selected["rule"]))
    w("Best F1 = {} attained at tau in {}.".format(
        fmt(selected["best_f1"]), selected["tied_on_f1"]))
    w("")
    w("| tau | Rel. | Eff. Rel. | Faith. | Faith. (ans.) | Abstain | Hall. | "
      "P | R | F1 | Spec. | Acc. | MCC |")
    w("|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for row in sweep:
        mark = " *" if row["threshold"] == tau else ""
        w("| {:.2f}{} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} |".format(
            row["threshold"], mark,
            fmt(row["relevance"]), fmt(row["eff_relevance"]),
            fmt(row["faithfulness"]), fmt(row["eff_faithfulness"]),
            fmt(row["abstain_rate"]), fmt(row["hallucination_rate"]),
            fmt(row["precision"]), fmt(row["recall"]), fmt(row["f1"]),
            fmt(row["specificity"]), fmt(row["accuracy"]), fmt(row["mcc"])))
    w("")
    w("LaTeX body for the subset of thresholds the original paper reported:")
    w("")
    w("```latex")
    for row in sweep:
        if row["threshold"] not in config.PAPER_THRESHOLDS:
            continue
        w("{:.2f} & {} & {} & {} & {} & {} & {} & {} & {} & {} & {} \\\\".format(
            row["threshold"],
            fmt(row["relevance"]), fmt(row["eff_relevance"]),
            fmt(row["faithfulness"]), fmt(row["abstain_rate"]),
            fmt(row["precision"]), fmt(row["recall"]), fmt(row["f1"]),
            fmt(row["specificity"]), fmt(row["accuracy"]), fmt(row["mcc"])))
    w("```")
    w("")

    # ---------------------------------------------------------- Table V
    w("## Table V -- Results by category (tau = {})".format(tau))
    w("")
    w("| Category | n | Abstain rate | Gen. refusals | Relevance | "
      "Faithfulness | Mean confidence |")
    w("|---|---:|---:|---:|---:|---:|---:|")
    for row in numbers["by_category"]:
        w("| {} | {} | {} | {} | {} | {} | {} |".format(
            CATEGORY_LABELS.get(row["category"], row["category"]), row["n"],
            fmt(row["abstain_rate"]), row["generator_refusals"],
            fmt(row["relevance"]), fmt(row["faithfulness"]),
            fmt(row["mean_confidence"], 3)))
    w("")

    # ------------------------------------------------- abstention detail
    w("## Abstention decision at tau* = {}".format(tau))
    w("")
    w("| | Value |")
    w("|---|---:|")
    w("| TP (should abstain, did) | {} |".format(a["tp"]))
    w("| FP (should answer, abstained) | {} |".format(a["fp"]))
    w("| TN (should answer, answered) | {} |".format(a["tn"]))
    w("| FN (should abstain, answered) | {} |".format(a["fn"]))
    w("| Labelled queries | {} |".format(a["n_labelled"]))
    w("| Precision | {} |".format(fmt(a["precision"])))
    w("| Recall | {} |".format(fmt(a["recall"])))
    w("| F1 | {} |".format(fmt(a["f1"])))
    w("| Specificity | {} |".format(fmt(a["specificity"])))
    w("| Accuracy | {} |".format(fmt(a["accuracy"])))
    w("| MCC | {} |".format(fmt(a["mcc"])))
    w("")

    # ----------------------------------------------- confidence by class
    w("## Confidence separation by class")
    w("")
    groups = [
        ("Answerable (in-domain)", lambda x: x["answerable"] is True),
        ("Uncertain (in-domain hard)", lambda x: x["answerable"] == "uncertain"),
        ("Unanswerable (near-miss)",
         lambda x: x["answerable"] is False and x["category"] == "near_miss"),
        ("Unanswerable (out-of-domain)",
         lambda x: x["answerable"] is False and x["category"] == "out_of_domain"),
    ]
    w("| Class | n | min | mean | max |")
    w("|---|---:|---:|---:|---:|")
    stats = {}
    for label, pred in groups:
        v = [x["confidence"] for x in records if pred(x)]
        if not v:
            continue
        stats[label] = v
        w("| {} | {} | {} | {} | {} |".format(
            label, len(v), fmt(min(v), 3), fmt(sum(v) / len(v), 3), fmt(max(v), 3)))
    w("")
    ans = stats.get("Answerable (in-domain)", [])
    nm = stats.get("Unanswerable (near-miss)", [])
    ood = stats.get("Unanswerable (out-of-domain)", [])
    if ans and ood:
        w("- Answerable floor minus out-of-domain ceiling: **{}** "
          "(positive means a clean gap).".format(fmt(min(ans) - max(ood), 3)))
    if ans and nm:
        gap = min(ans) - max(nm)
        w("- Answerable floor minus near-miss ceiling: **{}** "
          "(negative means the classes overlap and no threshold separates "
          "them).".format(fmt(gap, 3)))
        if gap < 0:
            below = sum(1 for v in ans if v <= max(nm))
            w("- {} of {} answerable queries score at or below the "
              "highest-scoring near-miss query.".format(below, len(ans)))
    w("")

    # ---------------------------------------------------------- variants
    if variants:
        w("## Confidence-score variants and chance level")
        w("")
        w("| c(q) | tau* | P | R | F1 | Spec. | Acc. | MCC |")
        w("|---|---:|---:|---:|---:|---:|---:|---:|")
        for label, m in variants["variants"].items():
            w("| {} | {:.2f} | {} | {} | {} | {} | {} | {} |".format(
                label, m["selected_threshold"], fmt(m["precision"]),
                fmt(m["recall"]), fmt(m["f1"]), fmt(m["specificity"]),
                fmt(m["accuracy"]), fmt(m["mcc"])))
        w("")
        cb = variants["chance_baseline"]
        w("Chance level at tau* = {}, matched to the same number of "
          "abstentions ({} of {} labelled queries), averaged over {} random "
          "trials:".format(cb["threshold"], cb["n_abstained"], cb["n_labelled"],
                           variants["random_trials"]))
        w("")
        w("| | P | R | F1 | Spec. | Acc. | MCC |")
        w("|---|---:|---:|---:|---:|---:|---:|")
        for label, key in (("Confidence gate", "confidence_gate"),
                           ("Random", "random")):
            m = cb[key]
            w("| {} | {} | {} | {} | {} | {} | {} |".format(
                label, fmt(m["precision"]), fmt(m["recall"]), fmt(m["f1"]),
                fmt(m["specificity"]), fmt(m["accuracy"]), fmt(m["mcc"])))
        w("")

    # ---------------------------------------------------- notable cases
    w("## Confident but wrong: substantive answers the judge scored below {:.0f}"
      .format(config.HALLUCINATION_FAITHFULNESS_CUTOFF))
    w("")
    w("These are the queries that passed the confidence gate, were answered "
      "with an actual assertion, and were still judged unfaithful. Generator "
      "refusals are excluded, so this list matches the hallucination count in "
      "Table II exactly.")
    w("")
    bad = [x for x in records
           if x["confidence"] >= tau
           and x["faithfulness"] is not None
           and x["faithfulness"] < config.HALLUCINATION_FAITHFULNESS_CUTOFF
           and not is_generator_refusal(x.get("rag_answer", ""))]
    if not bad:
        w("None.")
    for x in bad:
        w("- **{}** ({}, answerable={}) conf {} -- faithfulness {}, "
          "relevance {}".format(x["id"], x["category"], x["answerable"],
                                fmt(x["confidence"], 3), fmt(x["faithfulness"], 0),
                                fmt(x["relevance"], 0)))
        w("  - Q: {}".format(x["question"]))
        w("  - A: {}".format((x["rag_answer"] or "").replace("\n", " ")[:300]))
    w("")

    # ------------------------------------------- judge validation
    validation_path = config.JUDGE_VALIDATION_FILE
    if os.path.exists(validation_path):
        validation = read(validation_path)
        ratings = read(config.HUMAN_RATINGS_FILE)
        w("## Table VI -- Human vs. LLM-judge agreement")
        w("")
        w("| Metric | n | MAE | Exact | Pearson r | Spearman rho | Quadratic kappa |")
        w("|---|---:|---:|---:|---:|---:|---:|")
        for name in ("relevance", "faithfulness"):
            if name not in validation:
                continue
            s = validation[name]
            w("| {} | {} | {} | {} | {} | {} | {} |".format(
                name.capitalize(), s["n"], fmt(s["mae"]), fmt(s["exact_match"]),
                fmt(s["pearson_r"]), fmt(s["spearman_rho"]),
                fmt(s["quadratic_kappa"])))
        w("")
        w("```latex")
        for name in ("relevance", "faithfulness"):
            if name not in validation:
                continue
            s = validation[name]
            w("{} & {} & {} & {} & {} & {} \\\\".format(
                name.capitalize(), fmt(s["mae"]), fmt(s["exact_match"]),
                fmt(s["pearson_r"]), fmt(s["spearman_rho"]),
                fmt(s["quadratic_kappa"])))
        w("```")
        w("")
        disagreements = []
        for item in ratings:
            for axis in ("relevance", "faithfulness"):
                h, j = item.get("human_" + axis), item.get("judge_" + axis)
                if h is not None and j is not None and float(h) != float(j):
                    disagreements.append((item["id"], item["category"], axis, h, j))
        w("{} of {} rated items × 2 axes disagree ({} exact agreements out of "
          "{} judgements):".format(
              len(disagreements), len(ratings),
              2 * len(ratings) - len(disagreements), 2 * len(ratings)))
        w("")
        w("| Item | Category | Axis | Human | Judge |")
        w("|---|---|---|---:|---:|")
        for qid, cat, axis, h, j in disagreements:
            w("| {} | {} | {} | {:.0f} | {:.0f} |".format(qid, cat, axis, h, j))
        w("")
        w("Ratings were made by one author against the rubric in "
          "`src/evaluate.py` without consulting the judge's scores, on a "
          "seeded sample stratified across categories with generator refusals "
          "excluded (faithfulness is undefined for a refusal).")
        w("")

    # --------------------------- the judge's behaviour on refusals
    w("## The judge is not self-consistent on refusals")
    w("")
    w("A refusal asserts nothing, so the faithfulness rubric -- which scores "
      "whether an assertion is supported by the context -- has no defined "
      "behaviour on one. The judge's scores bear that out, which is why "
      "refusals are excluded from both the numerator and the denominator of "
      "every hallucination rate reported above.")
    w("")
    refusals = [x for x in records if is_generator_refusal(x.get("rag_answer", ""))]
    if refusals:
        dist = {}
        for x in refusals:
            dist[x["faithfulness"]] = dist.get(x["faithfulness"], 0) + 1
        w("| Faithfulness the judge assigned a refusal | Count |")
        w("|---:|---:|")
        for score in sorted(dist, key=lambda v: (v is None, v)):
            w("| {} | {} |".format("unparsed" if score is None else "{:.0f}".format(score),
                                   dist[score]))
        w("")
        w("- {} generator refusals in total, spread over {} distinct "
          "faithfulness scores.".format(len(refusals), len(dist)))
        # The same literal answer string scored differently is the sharpest
        # form of the point, so find it rather than asserting it.
        by_text = {}
        for x in refusals:
            by_text.setdefault((x["rag_answer"] or "").strip().lower(), set()).add(
                x["faithfulness"])
        split = {t: s for t, s in by_text.items() if len(s) > 1}
        for text, scores in sorted(split.items(), key=lambda kv: -len(kv[1]))[:3]:
            w('- The identical answer "{}" was scored {} on different '
              "queries, at temperature 0 under one judge model.".format(
                  text[:70], sorted("{:.0f}".format(v) for v in scores if v is not None)))
        if not split:
            w("- No single refusal string drew more than one distinct score in "
              "this run.")
        left_in = sum(1 for x in refusals
                      if x["confidence"] >= tau
                      and x["faithfulness"] is not None
                      and x["faithfulness"] < config.HALLUCINATION_FAITHFULNESS_CUTOFF)
        w("- Counting refusals as hallucinations would add **{}** spurious "
          "cases to the RAG hallucination count of {}, inflating it to {}."
          .format(left_in, c["rag_hallucinations"],
                  c["rag_hallucinations"] + left_in))
    else:
        w("No generator refusals occurred in this run.")
    w("")

    w("## Files")
    w("")
    for path in [config.PER_QUERY_FILE, config.PAPER_NUMBERS_FILE,
                 config.THRESHOLD_EXPERIMENT_FILE, config.SELECTED_THRESHOLD_FILE,
                 config.RETRIEVAL_METRICS_FILE, config.CATEGORY_RESULTS_FILE,
                 config.OUTPUT_FILE, config.FINAL_PLOT_FILE,
                 config.THRESHOLD_PLOT_FILE, config.CONFIDENCE_PLOT_FILE]:
        w("- `{}`".format(os.path.relpath(path, config.BASE_DIR).replace("\\", "/")))
    w("")

    out = os.path.join(config.BASE_DIR, "REVISION_RESULTS.md")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    print("Saved {}".format(out))


if __name__ == "__main__":
    main()
